### PR TITLE
Conflict (409) status code implementation, tests, docs (#1)

### PR DESCRIPTION
**Pull request by Teodor92**

### CODE REVIEW

**Comment by ivaylokenov** [comment]
@Teodor92 For some reason conflict result has conflicts (pun intended). Can you sort them out?

**Comment by Teodor92** [comment]
@ivaylokenov Merged with master - there should be no more conflicts.

**Comment by ivaylokenov** [comment]
@Teodor92 Still gives errors in the `ClientErrorControllerBaseExtensionsTest.cs` class. I believe it is because of a merged pull request before yours.

**Comment by Teodor92** [comment]
@ivaylokenov Fixed :)

**Comment by ivaylokenov** [comment]
Merged the conflict! Thanks! 👍

**Pull request merged**
